<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('articles')->insert([
            [
                'Titre' => 'PS5 FAT',
                'Price' => '5500 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps5_fatjpg.jpg',
                'Contenu' => 'The Playstation 5 GPU is a high-end gaming console graphics solution by AMD, launched on November 12th, 2020',
                'Solde' => True,
            ],
            [
                'Titre' => 'PS5 SLIM',
                'Price' => '6500 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps5_slim.jpg',
                'Contenu' => 'Sony Playstation 5 SLIM is a solid-state drive in the Embedded form factor, launched on October 31st, 2023.',
                'Solde' => False,
            ],
            [
                'Titre' => 'PS5 PRO',
                'Price' => '10000 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps5_pro.jpg',
                'Contenu' => 'With the PlayStation®5 Pro console, the world’s greatest game creators can enhance their games with incredible features like advanced ray tracing, super sharp image clarity for your 4K TV, and high frame rate gameplay.',
                'Solde' => False,
            ],
            [
                'Titre' => 'PS4 Slim Special Edition',
                'Price' => '5000 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps4_sp.jpg',
                'Contenu' => 'The PS4 Slim was announced by Sony on September 7, 2016 and was made available to the public on September 15, 2016. It is a revision to the PS4 model with a smaller form.',
                'Solde' => False,
            ],
            [
                'Titre' => 'PS3 Slim Yakuza Edition',
                'Price' => '6000 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps3_ys.jpg',
                'Contenu' => 'The PlayStation 3 (PS3) is a home video game console developed and marketed by Sony Computer Entertainment (SCE) in 11 september 2006.',
                'Solde' => True,
            ],
            [
                'Titre' => 'PS2 Ocean Blue Edition',
                'Price' => '3000 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps2_oss.jpg',
                'Contenu' => 'The PlayStation 2 (PS2) is a home video game console developed and marketed by Sony Computer Entertainment. It was first released in Japan on 4 March 2000.',
                'Solde' => True,
            ],
            [
                'Titre' => 'Devil May Cry 3 ',
                'Price' => '90 DH',
                'Categorie' => 'Games',
                'Img' => '/img/dmc3.jpg',
                'Contenu' => 'Action , Hack And Slash',
                'Solde' => True,
            ], [
                'Titre' => 'Dark Souls 1 : Prepare To Die Edition',
                'Price' => '100 DH',
                'Categorie' => 'Games',
                'Img' => '/img/ds1.jpg',
                'Contenu' => 'Hard, Action , RPG',
                'Solde' => false,
            ],
            [
                'Titre' => 'Katana Zero',
                'Price' => '50 DH',
                'Categorie' => 'Games',
                'Img' => '/img/kz.jpg',
                'Contenu' => 'Action , Platforming, Stealth',
                'Solde' => false,
            ],
            [
                'Titre' => 'Resident Evil 3 Nemesis',
                'Price' => '200 DH',
                'Categorie' => 'Games',
                'Img' => '/img/rs3.jpg',
                'Contenu' => 'Action , Survival Horror',
                'Solde' => false,
            ],
            [
                'Titre' => 'Silent Hill 2 Remake',
                'Price' => '800 DH',
                'Categorie' => 'Games',
                'Img' => '/img/sl2.jpg',
                'Contenu' => 'Action , Survival Horror, Psychological Horror',
                'Solde' => false,
            ],
            [
                'Titre' => 'Doom Eternal',
                'Price' => '200 DH',
                'Categorie' => 'Games',
                'Img' => '/img/doom.jpg',
                'Contenu' => 'Action , Platforming',
                'Solde' => false,
            ],
            [
                'Titre' => 'Elden Ring',
                'Price' => '800 DH',
                'Categorie' => 'Games',
                'Img' => '/img/elden.jpg',
                'Contenu' => 'Action , Souls, Hard , Action , RPG',
                'Solde' => false,
            ],
            [
                'Titre' => 'Need For Speed Most Wanted 2005',
                'Price' => '100 DH',
                'Categorie' => 'Games',
                'Img' => '/img/nfsmw.jpg',
                'Contenu' => 'Action , Fast Pace',
                'Solde' => false,
            ],
            [
                'Titre' => 'Cyberpunk PS4',
                'Price' => '515 DH',
                'Categorie' => 'Games',
                'Img' => 'https://i.ebayimg.com/images/g/xyoAAOSw2~1hl~OM/s-l1200.jpg',
                'Contenu' => 'Action , Adventure , Future',
                'Solde' => false,
            ],
            [
                'Titre' => 'Antec NX200M RGB MATX Mini Tower Gaming Case RTX 5090 i9-14F',
                'Price' => '20690 DH',
                'Categorie' => 'Setup',
                'Img' => 'https://gallerypanda.com/cdn/shop/files/F2ZjQ3NWEAEiXo6_8c42ca96-aaf7-4d72-aaf0-5f4986d46b9a.jpg?v=1705388692&width=1500',
                'Contenu' => 'Fantastic ',
                'Solde' => True,
            ],
            [
                'Titre' => 'Steelseries Aerox 9 Wireless Gaming Mouse',
                'Price' => '490 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://preview.redd.it/decided-to-personalize-my-ps5-controller-and-im-not-v0-704wpt1tc3ma1.jpg?width=1080&crop=smart&auto=webp&s=a2af56797bb0b7f5a0669a751fb16c926adc71cb',
                'Contenu' => 'Amazing ,PowerFull , Smooth',
                'Solde' => True,
            ],
            [
                'Titre' => '8TB Seagate Game Drive Hub For Xbox',
                'Price' => '290 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://assets2.razerzone.com/images/pnx.assets/57c2af30b5d9a2b699b3e896b788e00f/headset-landingpg-500x500-blacksharkv2pro2023.jpg',
                'Contenu' => 'Amazing ,PowerFull ',
                'Solde' => false,
            ],
            [
                'Titre' => 'Desktop Chair RGB ',
                'Price' => '4990 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://xrocker.co.uk/cdn/shop/files/AgilityRGBUpdated_1000x1000_crop_center.jpg?v=1695979579',
                'Contenu' => 'Amazing ,PowerFull , Hard ',
                'Solde' => True ,
            ],
            [
                'Titre' => 'Jojo Bizzare MousePad',
                'Price' => '290 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://m.media-amazon.com/images/I/71P2wCDQd7L._AC_UF1000,1000_QL80_.jpg',
                'Contenu' => 'Amazing , Peak  ',
                'Solde' => false,
            ],
            [
                'Titre' => 'PS5 Controller Special Edition',
                'Price' => '700 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://i.etsystatic.com/23929459/r/il/27eb1c/3873847320/il_570xN.3873847320_pqyx.jpg',
                'Contenu' => 'Amazing ,PowerFull ',
                'Solde' => false,
            ],
            [
                'Titre' => 'Gaming Headset Razor',
                'Price' => '290 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://assets2.razerzone.com/images/pnx.assets/725e74dcdcd6b8abcba3d5eca5d31809/razer-kraken-v4-500x500.webp',
                'Contenu' => 'Controll Your Sound  ',
                'Solde' => True,
            ],
            [
                'Titre' => 'BattleTron Gaming Mouse ',
                'Price' => 'Free',
                'Categorie' => 'Accescoires',
                'Img' => 'https://www.notebook-outlet.cz/fotky85110/fotos/_vyr_1644_IMG_20240125_084149.jpg',
                'Contenu' => 'Amazing ,PowerFull , Smooth ',
                'Solde' => false,
            ],
            [
                'Titre' => 'VR Headset',
                'Price' => '999 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://cdn.thewirecutter.com/wp-content/media/2024/10/vrheadsets-2048px-08406.jpg',
                'Contenu' => 'New Module ',
                'Solde' => false,
            ],
            [
                'Titre' => 'FC 25',
                'Price' => '400 DH',
                'Categorie' => 'Games',
                'Img' => 'https://pbs.twimg.com/media/GStAKw_WIAAbjOc.jpg:large',
                'Contenu' => 'Football , Sport',
                'Solde' => true,
            ],
            [
                'Titre' => 'UNCHARTED 4',
                'Price' => '200 DH',
                'Categorie' => 'Games',
                'Img' => 'https://www.gamespot.com/a/uploads/scale_super/43/434805/2876987-uncharted4amazon.jpg',
                'Contenu' => 'Action , Adventure',
                'Solde' => true,
            ],
            [
                'Titre' => 'Spider Man 2',
                'Price' => '400 DH',
                'Categorie' => 'Games',
                'Img' => 'https://preview.redd.it/created-a-high-quality-mobile-wallpaper-from-the-spider-man-v0-wjnga0a9dweb1.png?auto=webp&s=6f8d9a0a8890247dfadb598be677340a32e6305c',
                'Contenu' => 'Action , Adventure',
                'Solde' => true,
            ],
            [
                'Titre' => 'BLACK PS2',
                'Price' => '100 DH',
                'Categorie' => 'Games',
                'Img' => 'https://cdn.mobygames.com/covers/4424779-black-playstation-2-front-cover.jpg',
                'Contenu' => 'Football , Sport',
                'Solde' => true,
            ],
            [
                'Titre' => 'PES 2012',
                'Price' => '50 DH',
                'Categorie' => 'Games',
                'Img' => 'https://www.dsogaming.com/wp-content/uploads/2011/09/PES2012_PS2_Packshot_OB_bwin_UK___Italy_PEGI3_-_RGB.jpg',
                'Contenu' => 'Football , Sport',
                'Solde' => false,
            ],
            [
                'Titre' => 'Assasins Creed 2',
                'Price' => '100 DH',
                'Categorie' => 'Games',
                'Img' => 'https://cdn1.epicgames.com/salesEvent/salesEvent/AC2_GameName_Store_Portrait_1200x1600_1200x1600-2c5e000213988c5dde375bb2602e9986',
                'Contenu' => 'Action , Adventure',
                'Solde' => true,
            ],
            [
                'Titre' => 'GTA 6',
                'Price' => '1000 DH',
                'Categorie' => 'Games',
                'Img' => 'https://assets-prd.ignimgs.com/2023/12/06/gta6-ign-1701824432629.jpg',
                'Contenu' => 'Action , Adventure',
                'Solde' => false,
            ],
            [
                'Titre' => 'RTX 4060 Ryzen 5 5500 ',
                'Price' => '7000 DH',
                'Categorie' => 'Setup',
                'Img' => 'https://www.nebulapc.com.au/cdn/shop/files/HyperionNEW-7.jpg?v=1715587581',
                'Contenu' => 'ECONIMIQUAL',
                'Solde' => True,
            ],
            [
                'Titre' => 'RTX 4090 Ryzen 7 7900X ',
                'Price' => '20000 DH',
                'Categorie' => 'Setup',
                'Img' => 'https://geekawhat.com/wp-content/uploads/2024/07/FI_Cougar-FV270-RTX-4090-Build.jpg',
                'Contenu' => 'High End',
                'Solde' => True,
            ],

            [
                'Titre' => 'RTX 4080 Super Intel Core i9-12900KS ',
                'Price' => '18500 DH',
                'Categorie' => 'Setup',
                'Img' => 'https://danscustombuiltgamingbeasts.com/cdn/shop/files/IMG_9255.jpg?v=1706810617&width=1946',
                'Contenu' => 'Mid End',
                'Solde' => false,
            ],


        ]);
    }
}