<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('articles')->insert([
            // ===== CONSOLES =====
            [
                'Titre' => 'PS5 FAT',
                'Price' => '5500 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps5_fatjpg.jpg',
                'Contenu' => 'The Playstation 5 GPU is a high-end gaming console graphics solution by AMD, launched on November 12th, 2020',
                'Solde' => true,
            ],
            [
                'Titre' => 'PS5 SLIM',
                'Price' => '6500 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps5_slim.jpg',
                'Contenu' => 'Sony Playstation 5 SLIM is a solid-state drive in the Embedded form factor, launched on October 31st, 2023.',
                'Solde' => false,
            ],
            [
                'Titre' => 'PS5 PRO',
                'Price' => '10000 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps5_pro.jpg',
                'Contenu' => 'With the PlayStation®5 Pro console, the world\'s greatest game creators can enhance their games with incredible features like advanced ray tracing, super sharp image clarity for your 4K TV, and high frame rate gameplay.',
                'Solde' => false,
            ],
            [
                'Titre' => 'PS4 Slim Special Edition',
                'Price' => '5000 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps4_sp.jpg',
                'Contenu' => 'The PS4 Slim was announced by Sony on September 7, 2016 and was made available to the public on September 15, 2016. It is a revision to the PS4 model with a smaller form.',
                'Solde' => false,
            ],
            [
                'Titre' => 'PS3 Slim Yakuza Edition',
                'Price' => '6000 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps3_ys.jpg',
                'Contenu' => 'The PlayStation 3 (PS3) is a home video game console developed and marketed by Sony Computer Entertainment (SCE) in 11 september 2006.',
                'Solde' => true,
            ],
            [
                'Titre' => 'PS2 Ocean Blue Edition',
                'Price' => '3000 DH',
                'Categorie' => 'Consoles',
                'Img' => '/img/ps2_oss.jpg',
                'Contenu' => 'The PlayStation 2 (PS2) is a home video game console developed and marketed by Sony Computer Entertainment. It was first released in Japan on 4 March 2000.',
                'Solde' => true,
            ],

            // ===== COMPONENTS (From BD DEMO.txt) =====
            [
                'Titre' => 'RTX 5090',
                'Price' => '9000 DH',
                'Categorie' => 'Components',
                'Img' => '/img/MSI 5090.jpg',
                'Contenu' => 'Nvidia, MSI',
                'Solde' => true,
            ],
            [
                'Titre' => 'RTX 5070 TI',
                'Price' => '7000 DH',
                'Categorie' => 'Components',
                'Img' => '/img/ASUS 5070 TI.jpg',
                'Contenu' => 'Nvidia, Asus',
                'Solde' => true,
            ],
            [
                'Titre' => 'RTX 4060',
                'Price' => '3000 DH',
                'Categorie' => 'Components',
                'Img' => '/img/MSI 4060.jpg',
                'Contenu' => 'Nvidia MSI',
                'Solde' => false,
            ],
            [
                'Titre' => 'RX 6600',
                'Price' => '2500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/RX 6600 GIGA BYTE.png',
                'Contenu' => 'AMD, GIGABYTE',
                'Solde' => false,
            ],
            [
                'Titre' => 'RTX 3060 TI',
                'Price' => '3500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/3060 TI.png',
                'Contenu' => 'Nvidia, GIGABYTE',
                'Solde' => true,
            ],
            [
                'Titre' => 'RX 9070',
                'Price' => '6500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/RX 9070.jpg',
                'Contenu' => 'AMD, GIGABYTE',
                'Solde' => false,
            ],
            [
                'Titre' => 'Ryzen 5 3600',
                'Price' => '800 DH',
                'Categorie' => 'Components',
                'Img' => '/img/r5 3600.jpg',
                'Contenu' => 'AMD',
                'Solde' => true,
            ],
            [
                'Titre' => 'Ryzen 7 5800',
                'Price' => '2500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/r7 5800.jpg',
                'Contenu' => 'AMD',
                'Solde' => false,
            ],
            [
                'Titre' => 'Ryzen 9 950X3D',
                'Price' => '7500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/r9 9950XD.jpg',
                'Contenu' => 'AMD',
                'Solde' => false,
            ],
            [
                'Titre' => 'Ryzen 5 5600X',
                'Price' => '1200 DH',
                'Categorie' => 'Components',
                'Img' => '/img/r5 5600X.jpg',
                'Contenu' => 'AMD',
                'Solde' => false,
            ],
            [
                'Titre' => 'Intel 7 12700 k',
                'Price' => '3100 DH',
                'Categorie' => 'Components',
                'Img' => '/img/intel-core-i7.jpg',
                'Contenu' => 'Intel',
                'Solde' => false,
            ],
            [
                'Titre' => 'Intel 5 12600k',
                'Price' => '2400 DH',
                'Categorie' => 'Components',
                'Img' => '/img/intel-core-i5-12600k.jpg',
                'Contenu' => 'Intel',
                'Solde' => false,
            ],
            [
                'Titre' => 'Intel 5 10600k',
                'Price' => '2400 DH',
                'Categorie' => 'Components',
                'Img' => '/img/I5 10600K.jpg',
                'Contenu' => 'Intel',
                'Solde' => false,
            ],
            [
                'Titre' => 'Intel 9 14900k',
                'Price' => '6400 DH',
                'Categorie' => 'Components',
                'Img' => '/img/intel-core-i9.jpg',
                'Contenu' => 'Intel',
                'Solde' => false,
            ],
            [
                'Titre' => 'ONE PIECE CASE',
                'Price' => '1400 DH',
                'Categorie' => 'Components',
                'Img' => '/img/ONE PIECE CASE.jpg',
                'Contenu' => 'ASUS',
                'Solde' => false,
            ],
            [
                'Titre' => 'EVANGELION CASE',
                'Price' => '1800 DH',
                'Categorie' => 'Components',
                'Img' => '/img/EVANGELION.jpg',
                'Contenu' => 'HYBROK',
                'Solde' => false,
            ],
            [
                'Titre' => 'ASUS ROG STRIX CASE',
                'Price' => '2400 DH',
                'Categorie' => 'Components',
                'Img' => '/img/ASUS CASE.png',
                'Contenu' => 'ASUS',
                'Solde' => false,
            ],
            [
                'Titre' => 'MSI NEXUS CASE',
                'Price' => '2500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/MSI CASE.jpg',
                'Contenu' => 'MSI',
                'Solde' => false,
            ],
            [
                'Titre' => 'MSI PRO -B760',
                'Price' => '2500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/msi-pro-b760.jpg',
                'Contenu' => 'MSI',
                'Solde' => false,
            ],
            [
                'Titre' => 'B450M DS3H',
                'Price' => '2000 DH',
                'Categorie' => 'Components',
                'Img' => '/img/B450M_DS3H.jpg',
                'Contenu' => 'GIGABYTE',
                'Solde' => false,
            ],
            [
                'Titre' => 'ASUS B450M - PLUS',
                'Price' => '3500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/ASUS B450M - PLUS.jpg',
                'Contenu' => 'ASUS',
                'Solde' => false,
            ],
            [
                'Titre' => 'B650SE -AORUS',
                'Price' => '2700 DH',
                'Categorie' => 'Components',
                'Img' => '/img/B650SE -AORUS.jpg',
                'Contenu' => 'AORUS',
                'Solde' => false,
            ],
            [
                'Titre' => 'AMD Wraith Stealth',
                'Price' => '0 DH',
                'Categorie' => 'Components',
                'Img' => '/img/amd-wraith-stealth.jpg',
                'Contenu' => 'AMD Stock Cooler',
                'Solde' => false,
            ],
            [
                'Titre' => 'Cooler Master Hyper 212',
                'Price' => '300 DH',
                'Categorie' => 'Components',
                'Img' => '/img/cooler-master-hyper-212.jpg',
                'Contenu' => 'Popular CPU Air Cooler',
                'Solde' => false,
            ],
            [
                'Titre' => 'NZXT Kraken X53',
                'Price' => '1200 DH',
                'Categorie' => 'Components',
                'Img' => '/img/nzxt-kraken-x53.jpg',
                'Contenu' => 'Premium AIO Liquid Cooler',
                'Solde' => false,
            ],
            [
                'Titre' => 'XPG DDR5 16GB',
                'Price' => '500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/XPG DDR5 16GB.jpg',
                'Contenu' => 'AORUS',
                'Solde' => false,
            ],
            [
                'Titre' => 'Jhon Marston Mousepad',
                'Price' => '70 DH',
                'Categorie' => 'Accescoires',
                'Img' => '/img/Jhon.png',
                'Contenu' => 'Tough as a desert storm, smooth as a six-shooter’s draw. Whether you’re gaming or working,Ride, shoot, or click—this pad’s seen worse.',
                'Solde' => true,
            ],
            [
                'Titre' => 'Arthur Morgan Mousepad',
                'Price' => '70 DH',
                'Categorie' => 'Accescoires',
                'Img' => '/img/Arthur.png',
                'Contenu' => 'Dirt Resist , Powerful , Comftarble , ',
                'Solde' => false,
            ],
            [
                'Titre' => 'Asus White Keyboard RGB',
                'Price' => '500 DH',
                'Categorie' => 'Accescoires',
                'Img' => '/img/ST60png-1100x1100.png',
                'Contenu' => 'SONIC Gaming Chair – Premium ergonomic design, plush cushioning, and ultra-supportive lumbar for marathon gaming sessions. Engineered for all-day comfort, cloud-like relaxation, and effortless adjustability!',
                'Solde' => false,
            ],
            [
                'Titre' => 'Sonic Gaming Chair',
                'Price' => '1800 DH',
                'Categorie' => 'Accescoires',
                'Img' => '/img/81EE3rfBKXL._SL1500_.jpg',
                'Contenu' => 'SONIC Gaming Chair – Premium ergonomic design, plush cushioning, and ultra-supportive lumbar for marathon gaming sessions. Engineered for all-day comfort, cloud-like relaxation, and effortless adjustability!',
                'Solde' => true,
            ],
 
            [
                'Titre' => 'RAZER GAMING HEADSET X105',
                'Price' => '800 DH',
                'Categorie' => 'Accescoires',
                'Img' => '/img/headset-landingpg-500x500-barracuda.jpg',
                'Contenu' => 'RAZER GAMING HEADSET – Crystal-clear THX Spatial Audio, plush memory foam ear cushions, and unrivaled noise isolation for immersive precision, pro-level clarity, and bone-rattling bass!',
                'Solde' => false,
            ],
           
            [
                'Titre' => 'ULTRA 9  RTX 5090',
                'Price' => '62000 DH',
                'Categorie' => 'Setup',
                'Img' => '/img/Ultra 9 (64gb-4TB) RTX 5090-1100x1100.png',
                'Contenu' => 'Intel Core Ultra 9 285K | MSI RTX 5090 32GB Vanguard SOC | XPG Lancer Blade DDR5 64GB (2x32GB) 6000MHz White | MSI Spatium M480 Pro 4TB NVMe | ASUS ROG Maximus Z890 Apex | HYTE Y70 Touch Infinite Snow White | ASUS ROG RYUJIN III 360 ARGB White AIO | Corsair HX1500i 1500W 80+ Platinum | Windows 11 Pro', 
                'Solde' => true,
            ],
            [
                'Titre' => 'ULTRA 7 RX 9070 XT',
                'Price' => '32000 DH ',
                'Categorie' => 'Setup',
                'Img' => '/img/builds234 (2)-1100x1100.png',
                'Contenu' => 'Intel Core Ultra 7 265F | Palit RTX 5070 Gaming Pro 12GB GDDR7 | XPG Lancer Blade RGB DDR5 32GB (2x16GB) 6000MHz Black | XPG GAMMIX S60 1TB NVMe | MSI Z890 GAMING PLUS WIFI | Azza Cube 802F RGB | EKWB EK-Nucleus CR240 Lux D-RGB Black | Cooler Master GX III 750W Gold | Windows 11 Pro', 
                'Solde' => false,
            ],
            [
                'Titre' => 'Azza Cube 5070',
                'Price' => '30000 DH',
                'Categorie' => 'Setup',
                'Img' => '/img/Azza Cube 5070 - Ultra 7-1100x1100.png',
                'Contenu' => 'Intel Core Ultra 7 265 | XFX Mercury RX 9070 XT MAG AIR 16GB White | XPG Lancer Blade RGB DDR5 32GB (2x16GB) 6000MHz CL48 White | XPG Gammix S70 Blade 1TB NVMe | MSI PRO Z890-P WIFI | Gamdias Neso P1 White | Gamdias Chione E4-240 White AIO | Gamdias Helios M1-850B 850W | Windows 11 Pro', 
                'Solde' => false,
            ],
            [
                'Titre' => 'Black Bundle 1 ',
                'Price' => '20000 DH',
                'Categorie' => 'Setup',
                'Img' => '/img/BLACK Bundle 1news-1100x1100.png',
                'Contenu' => 'Intel Core i5-12400F | GeForce RTX 4060 | XPG Spectrix D35G 16GB (2x8GB) 3600MHz | XPG GAMMIX S60 512GB NVMe | MSI PRO H610M-G DDR4 | Gamdias Talos E3 Mesh Black | Gamdias Boreas E1-410 Air Cooler | Gamdias Helios M1-650B 650W | Windows 11 Pro', 
                'Solde' => true,
            ],
            [
                'Titre' => 'XPG DDR5 16GB RGB',
                'Price' => '600 DH',
                'Categorie' => 'Components',
                'Img' => '/img/XPG DDR5 16GB RGB.png',
                'Contenu' => 'AORUS',
                'Solde' => false,
            ],
            [
                'Titre' => 'KINGSTON FURY DDR4 16GB',
                'Price' => '400 DH',
                'Categorie' => 'Components',
                'Img' => '/img/KING 16 GB RGB.jpg',
                'Contenu' => 'KINGSTON',
                'Solde' => false,
            ],
            [
                'Titre' => 'TOUGHRAM DDR4 16GB RGB',
                'Price' => '450 DH',
                'Categorie' => 'Components',
                'Img' => '/img/TOUGHRAM DDR4.jpg',
                'Contenu' => 'TOUGHRAM',
                'Solde' => false,
            ],
            [
                'Titre' => 'SG SATA3 SSD256GB',
                'Price' => '400 DH',
                'Categorie' => 'Components',
                'Img' => '/img/sg sata3.jpg',
                'Contenu' => 'SETUP GAME',
                'Solde' => true,
            ],
            [
                'Titre' => 'LEXAR 512SSD',
                'Price' => '100 DH',
                'Categorie' => 'Components',
                'Img' => '/img/LEXAR 512SSD.png',
                'Contenu' => 'LEXAR',
                'Solde' => false,
            ],
            [
                'Titre' => 'MSI SPATIUM 1TB',
                'Price' => '1000 DH',
                'Categorie' => 'Components',
                'Img' => '/img/MSI SPATIUM 1TB.jpg',
                'Contenu' => 'MSI',
                'Solde' => false,
            ],
            [
                'Titre' => 'Samsung SSD 2TB',
                'Price' => '2500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/samsung 2tb.jpg',
                'Contenu' => 'Samsung',
                'Solde' => true,
            ],

            [
                'Titre' => 'MSI B550M-A PRO ProSeries Motherboard',
                'Price' => '900 DH',
                'Categorie' => 'Components',
                'Img' => 'https://asset.msi.com/resize/image/global/product/product_1_20200818100208_5f3b36a02389e.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png',
                'Contenu' => 'Support 3rd Gen AMD Ryzen Desktop Processors and AMD Ryzen 4000 G-Series Desktop Processors',
                'Solde' => false,
            ],
            [
                'Titre' => 'AMD Ryzen™ 5 5600G 6-Core 12-Thread Desktop Processor with Radeon™ Graphics',
                'Price' => '1500 DH',
                'Categorie' => 'Components',
                'Img' => 'https://cdna.pcpartpicker.com/static/forever/images/product/1dd09dfdc581be6224a323d49d714c7f.jpg',
                'Contenu' => 'Play some of the most popular games at 1080p with the fastest processor graphics in the world, no graphics card required',
                'Solde' => false,
            ],
            [
                'Titre' => 'CORSAIR VENGEANCE LPX DDR4 RAM 16GB (2x8GB) 3200MHz CL16',
                'Price' => '360 DH',
                'Categorie' => 'Components',
                'Img' => 'https://cdna.pcpartpicker.com/static/forever/images/product/0d7ccc6bb32c1a857bdfc56d9eb74081.jpg',
                'Contenu' => 'Hand-sorted memory chips ensure high performance with generous Overclocking headroom.',
                'Solde' => false,
            ],
            [
                'Titre' => 'GeForce RTX 3060 Ventus 2X 12G OC',
                'Price' => '3200 DH',
                'Categorie' => 'Components',
                'Img' => 'https://cdna.pcpartpicker.com/static/forever/images/product/c740684e2cd2339bf845f7493711bcb7.jpg',
                'Contenu' => 'Get incredible performance with enhanced Ray Tracing Cores and Tensor Cores, new streaming multiprocessors, and high-speed G6 memory.',
                'Solde' => false,
            ],
            [
                'Titre' => 'Kingston NV3 1 TB M.2-2280 PCIe 4.0 X4 NVME Solid State Drive',
                'Price' => '650 DH',
                'Categorie' => 'Components',
                'Img' => 'https://cdna.pcpartpicker.com/static/forever/images/product/0a0b12a29d901a2fef4cd49748f3cc54.jpg',
                'Contenu' => 'Up to 6000 MB/s',
                'Solde' => false,
            ],
            [
                'Titre' => 'MSI MAG A550BN Gaming Power Supply - 80 Plus Bronze Certified 550W',
                'Price' => '640 DH',
                'Categorie' => 'Components',
                'Img' => 'https://cdna.pcpartpicker.com/static/forever/images/product/dbd0756d4475aa00b6d22220eff9201d.jpg',
                'Contenu' => '5-year limited warranty, guaranteeing long term reliable operation.',
                'Solde' => false,
            ],
            [
                'Titre' => 'MSI MPG A850G',
                'Price' => '1200 DH',
                'Categorie' => 'Components',
                'Img' => '/img/msi-mpg-a850g.jpg',
                'Contenu' => '80 Plus Gold Certified 850W Power Supply',
                'Solde' => false,
            ],
            [
                'Titre' => 'Corsair RM1000x',
                'Price' => '1500 DH',
                'Categorie' => 'Components',
                'Img' => '/img/corsair-rm1000x.jpg',
                'Contenu' => '80 Plus Gold Certified 1000W Power Supply',
                'Solde' => false,
            ],
            [
                'Titre' => 'Cooler Master MasterBox Q300L Micro-ATX Tower',
                'Price' => '400 DH',
                'Categorie' => 'Components',
                'Img' => 'https://cdna.pcpartpicker.com/static/forever/images/product/56e231eebb777b15c64c52cff2d07dfb.jpg',
                'Contenu' => 'Magnetic Dust Filters: The unique pattern of the dust filter adds a distinctive appearance to the case.',
                'Solde' => false,
            ],

            // ===== SETUP =====
            [
                'Titre' => 'Antec NX200M RGB MATX Mini Tower Gaming Case RTX 5090 i9-14F',
                'Price' => '20690 DH',
                'Categorie' => 'Setup',
                'Img' => 'https://gallerypanda.com/cdn/shop/files/F2ZjQ3NWEAEiXo6_8c42ca96-aaf7-4d72-aaf0-5f4986d46b9a.jpg?v=1705388692&width=1500',
                'Contenu' => 'Fantastic',
                'Solde' => true,
            ],
            [
                'Titre' => 'RTX 4060 Ryzen 5 5500',
                'Price' => '7000 DH',
                'Categorie' => 'Setup',
                'Img' => 'https://www.nebulapc.com.au/cdn/shop/files/HyperionNEW-7.jpg?v=1715587581',
                'Contenu' => 'ECONIMIQUAL',
                'Solde' => true,
            ],
            [
                'Titre' => 'RTX 4090 Ryzen 7 7900X',
                'Price' => '20000 DH',
                'Categorie' => 'Setup',
                'Img' => 'https://geekawhat.com/wp-content/uploads/2024/07/FI_Cougar-FV270-RTX-4090-Build.jpg',
                'Contenu' => 'High End',
                'Solde' => true,
            ],
            [
                'Titre' => 'RTX 4080 Super Intel Core i9-12900KS',
                'Price' => '18500 DH',
                'Categorie' => 'Setup',
                'Img' => 'https://danscustombuiltgamingbeasts.com/cdn/shop/files/IMG_9255.jpg?v=1706810617&width=1946',
                'Contenu' => 'Mid End',
                'Solde' => false,
            ],

            // ===== ACCESSORIES =====
            [
                'Titre' => 'Steelseries Aerox 9 Wireless Gaming Mouse',
                'Price' => '490 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://preview.redd.it/decided-to-personalize-my-ps5-controller-and-im-not-v0-704wpt1tc3ma1.jpg?width=1080&crop=smart&auto=webp&s=a2af56797bb0b7f5a0669a751fb16c926adc71cb',
                'Contenu' => 'Amazing, PowerFull, Smooth',
                'Solde' => true,
            ],
            [
                'Titre' => '8TB Seagate Game Drive Hub For Xbox',
                'Price' => '290 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://assets2.razerzone.com/images/pnx.assets/57c2af30b5d9a2b699b3e896b788e00f/headset-landingpg-500x500-blacksharkv2pro2023.jpg',
                'Contenu' => 'Amazing, PowerFull',
                'Solde' => false,
            ],
            [
                'Titre' => 'Desktop Chair RGB',
                'Price' => '4990 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://xrocker.co.uk/cdn/shop/files/AgilityRGBUpdated_1000x1000_crop_center.jpg?v=1695979579',
                'Contenu' => 'Amazing, PowerFull, Hard',
                'Solde' => true,
            ],
            [
                'Titre' => 'Jojo Bizzare MousePad',
                'Price' => '290 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://m.media-amazon.com/images/I/71P2wCDQd7L._AC_UF1000,1000_QL80_.jpg',
                'Contenu' => 'Amazing, Peak',
                'Solde' => false,
            ],
            [
                'Titre' => 'PS5 Controller Special Edition',
                'Price' => '700 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://i.etsystatic.com/23929459/r/il/27eb1c/3873847320/il_570xN.3873847320_pqyx.jpg',
                'Contenu' => 'Amazing, PowerFull',
                'Solde' => false,
            ],
            [
                'Titre' => 'Gaming Headset Razor',
                'Price' => '290 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://assets2.razerzone.com/images/pnx.assets/725e74dcdcd6b8abcba3d5eca5d31809/razer-kraken-v4-500x500.webp',
                'Contenu' => 'Controll Your Sound',
                'Solde' => true,
            ],
            [
                'Titre' => 'BattleTron Gaming Mouse',
                'Price' => 'Free',
                'Categorie' => 'Accescoires',
                'Img' => 'https://www.notebook-outlet.cz/fotky85110/fotos/_vyr_1644_IMG_20240125_084149.jpg',
                'Contenu' => 'Amazing, PowerFull, Smooth',
                'Solde' => false,
            ],
            [
                'Titre' => 'VR Headset',
                'Price' => '999 DH',
                'Categorie' => 'Accescoires',
                'Img' => 'https://cdn.thewirecutter.com/wp-content/media/2024/10/vrheadsets-2048px-08406.jpg',
                'Contenu' => 'New Module',
                'Solde' => false,
            ],
        ]);
    }
}
